# yaml-language-server: $schema=https://unpkg.com/@sveltia/cms/schema/sveltia-cms.json

backend:
  name: github
  repo: Meditation-Steps/host.dharmachakra.online
  branch: main
  base_url: https://sveltia-cms-auth.funbotan.workers.dev/

media_folder: static/images

i18n:
  structure: multiple_files
  locales: [en, ru]
  default_locale: en

collections:
  - name: svadhyaya
    label: Svadhyaya
    folder: static/svadhyaya
    format: raw
    extension: md
    create: false
    delete: false
    i18n: true
    fields:
      - { label: Body, name: body, widget: richtext, i18n: true }