media:
  input: static/images
  output: /images

content:
  - name: svadhyaya_en
    label: "Svadhyaya (English)"
    type: collection
    path: static/svadhyaya
    format: raw
    operations:
      create: false
      delete: false
    fields:
      - name: body
        label: Body
        type: rich-text

  - name: svadhyaya_ru
    label: "Svadhyaya (Russian)"
    type: collection
    path: static/svadhyaya
    format: raw
    operations:
      create: false
      delete: false
    fields:
      - name: body
        label: Body
        type: rich-text